apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts  # note: the oci:// syntax is not included.
    targetRevision: 7.0.0 
    helm:
      valuesObject:
        namespaceOverride: "grafana"
        service:
          port: 7890
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: grafana 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
