apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    targetRevision: 15.9.0
    helm:
      valuesObject:
        namespaceOverride: "nginx"
        service:
          type: NodePort 
          ports:
            http: 5678
        ingress:
          enabled: true
          hostname: hello-world.example
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
