apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus 
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts  # note: the oci:// syntax is not included.
    targetRevision: 25.28.0 
    helm:
      valuesObject:
        namespaceOverride: "monitoring"
        service:
          type: ClusterIP 
        ingress:
          enabled: true
          hosts: ["prometheus.test"]
        baseURL: "prometheus.test"
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
