apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus 
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts  # note: the oci:// syntax is not included.
    targetRevision: 25.28.0 
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        namespaceOverride: "monitoring"
        service:
          type: ClusterIP 
        server:
          extraArgs:
            - "--web.enable-lifecycle"
          ingress:
            ingressClassName: alb
            enabled: true
            hosts: ["prometheus.ci-dev.uktrade.digital"]
            annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/group.name: default
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
            alb.ingress.kubernetes.io/ssl-redirect: '443'
            external-dns.alpha.kubernetes.io/hostname: prometheus.ci-dev.uktrade.digital
          baseURL: "prometheus.ci-dev.uktrade.digital"
          persistentVolume:
            enabled: false
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
